---
- name: Install Jenkins, Docker, Trivy, Terraform, kubectl and AWS CLI
  hosts: localhost
  become: yes
  connection: local

  tasks:
    # Update APT cache and install basic packages
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - unzip
          - software-properties-common
          - openjdk-17-jdk
        state: present

    # -----------------------------
    # Docker Installation
    # -----------------------------
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    # -----------------------------
    # Jenkins Installation
    # -----------------------------
    - name: Add Jenkins GPG key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Add Jenkins APT repository
      apt_repository:
        repo: "deb https://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Update apt cache after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins is running
      service:
        name: jenkins
        state: started
        enabled: yes
    

    # -----------------------------
    # Trivy Installation
    # -----------------------------
    - name: Download Trivy
      get_url:
        url: https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
        dest: /tmp/trivy.deb

    - name: Install Trivy
      apt:
        deb: /tmp/trivy.deb

    # -----------------------------
    # Terraform Installation
    # -----------------------------
    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
        dest: /tmp/terraform.zip

    - name: Unzip Terraform binary
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'

    # -----------------------------
    # kubectl Installation
    # -----------------------------
    - name: Download kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    # -----------------------------
    # AWS CLI Installation
    # -----------------------------
    - name: Download AWS CLI
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip AWS CLI
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install AWS CLI
      command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws
